{% set name = "eslint-config-standard" %}
{% set version = "17.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/standard/eslint-config-standard/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0e006be24f276146706ae8d567c1cea1b9944df600676e9865fb44c629727c8c

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - test -d $PREFIX/lib/node_modules/eslint-config-standard  # [unix]
    - if not exist %LIBRARY_INC%\lib\node_modules\eslint-config-standard exit 1  # [win]

about:
  home: https://github.com/standard/eslint-config-standard
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Find and fix problems in your JavaScript code.

extra:
  recipe-maintainers:
    - xhochy
    - jens-ox
